package com.example.petadoptionmanagement.model

/**
 * Data class representing a Pet in the application.
 * This acts as the Model in the MVVM architecture.
 *
 * @property petId Unique identifier for the pet (generated by Firebase).
 * @property petName Name of the pet.
 * @property petBreed Breed of the pet.
 * @property petType Type of animal (e.g., Dog, Cat, Bird).
 * @property petAge Age of the pet.
 * @property petDescription Detailed description of the pet.
 * @property petStatus Current adoption status (e.g., Available, Adopted, Pending).
 * @property petImageUrl URL to the pet's image (will be stored in Firebase Storage).
 * @property adoptionId Unique identifier for the adoption record, if the pet is adopted.
 */
data class PetModel(
    var petId: String = "",
    var petName: String = "",
    var petBreed: String = "",
    var petType: String = "",
    var petAge: String = "",
    var petDescription: String = "",
    var petStatus: String = "",
    var petImageUrl: String = "",
    var adoptionId: String? = null, // Nullable, as not all pets are adopted initially
    val imageUrl: String
)