package com.example.petadoptionmanagement.model

/**
 * Represents a Pet record for adoption.
 *
 * Includes pet information, status, and adoption linkage.
 */
data class PetModel(
    var petId: String = "",                  // Unique ID generated by Firebase
    var petName: String = "",
    var petBreed: String = "",
    var petType: String = "",
    var petGender: String = "",
    var petAge: String = "",
    var petDescription: String = "",
    var petStatus: String = "Available",    // Default to "Available"; other states: "Pending Adoption", "Adopted"
    var petImageUrl: String = "",
    var adoptionId: String? = null,          // Optional: Link to adoption record
    var adopterId: String? = null,           // UserId of the adopter if adopted/pending
    var addedBy: String = "",                 // userId of who added the pet (admin)
    var timestamp: Long = System.currentTimeMillis()
) {
    // No-arg constructor for Firebase deserialization
    constructor() : this(
        petId = "",
        petName = "",
        petBreed = "",
        petType = "",
        petGender = "",
        petAge = "",
        petDescription = "",
        petStatus = "Available",
        petImageUrl = "",
        adoptionId = null,
        adopterId = null,
        addedBy = "",
        timestamp = System.currentTimeMillis()
    )
}
